import type { Metadata } from "next";
import { Bayon, Darker_Grotesque, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const bayon = Bayon({
  subsets: ["latin"],
  weight: "400",
  variable: '--font-bayon',
});

const darkerGrotesque = Darker_Grotesque({
  subsets: ["latin"],
  variable: '--font-darker-grotesque',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bayon.variable} ${darkerGrotesque.variable} antialiased `}>
        {children}
      </body>
    </html>
  );
}
