// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.3 scene.gltf --transform
// Files: scene.gltf [4.86KB] > /Users/mv/Downloads/soccer_ball/scene-transformed.glb [41.17KB] (-747%)
// Author: EA Sports (https://sketchfab.com/jhsgkdfhk)
// License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// Source: https://sketchfab.com/3d-models/soccer-ball-1122127afbf14972bbf1aaff59f353d1
// Title: Soccer Ball
// */

// import React from "react";
// import { useGLTF } from "@react-three/drei";
// import { useFrame } from "@react-three/fiber";

// export function EAModel(props) {
//   const group = React.useRef();
//   const { nodes, materials } = useGLTF("models/ea.glb");
//   const initialY = 0;
//   const floatAmplitude = 0.5;
//   const floatSpeed = 2;
//   const rotationSpeed = 0.3;
//   useFrame((state) => {
//     if (group.current) {
//       const time = state.clock.getElapsedTime();
//       group.current.position.y =
//         initialY + Math.sin(time * floatSpeed) * floatAmplitude;

//       group.current.rotation.y += rotationSpeed * 0.01;
//     }
//   });
//   return (
//     <group ref={group} {...props} dispose={null} scale={[50,50,50]}>
//       <mesh
//         geometry={nodes.Object_2.geometry}
//         material={materials["Material.001"]}
//         rotation={[-Math.PI / 2, 0, 0]}
//         scale={0.25}
//       />
//       <mesh
//         geometry={nodes.Object_3.geometry}
//         material={materials["Material.002"]}
//         rotation={[-Math.PI / 2, 0, 0]}
//         scale={0.25}
//       />
//     </group>
//   );
// }

// useGLTF.preload("models/ea.glb");

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [113.74KB] > /Users/mv/Downloads/neymar_dancing/scene-transformed.glb [498.52KB] (-338%)
Author: fenglier (https://sketchfab.com/lfenglier)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/neymar-dancing-57018fb834144e29a0957c8ddd27522e
Title: neymar dancing
*/

import React,{useEffect} from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function EAModel(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("models/neymar.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    // console.log(actions)
    //crawl, jump, swing to land
    const animation = actions["mixamo.com"];
    animation.timeScale = 0.75
    animation.setEffectiveWeight(100);
    animation.setLoop(true);
    animation.play();
  }, []);
  return (
    <group ref={group} {...props} dispose={null} scale={16} position={[-10,-20,0]}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh
          name="Object_7"
          geometry={nodes.Object_7.geometry}
          material={materials.Material__54}
          skeleton={nodes.Object_7.skeleton}
          scale={15.074}
        />
        <skinnedMesh
          name="Object_8"
          geometry={nodes.Object_8.geometry}
          material={materials.Material__88}
          skeleton={nodes.Object_8.skeleton}
          scale={15.074}
        />
        <skinnedMesh
          name="Object_9"
          geometry={nodes.Object_9.geometry}
          material={materials.Material__71}
          skeleton={nodes.Object_9.skeleton}
          scale={15.074}
        />
        <skinnedMesh
          name="Object_10"
          geometry={nodes.Object_10.geometry}
          material={materials.Material__105}
          skeleton={nodes.Object_10.skeleton}
          scale={15.074}
        />
        <skinnedMesh
          name="Object_11"
          geometry={nodes.Object_11.geometry}
          material={materials.Material__122}
          skeleton={nodes.Object_11.skeleton}
          scale={15.074}
        />
        <skinnedMesh
          name="Object_12"
          geometry={nodes.Object_12.geometry}
          material={materials.Material__156}
          skeleton={nodes.Object_12.skeleton}
          scale={15.074}
        />
        <skinnedMesh
          name="Object_13"
          geometry={nodes.Object_13.geometry}
          material={materials.Material__156}
          skeleton={nodes.Object_13.skeleton}
          scale={15.074}
        />
        <skinnedMesh
          name="Object_14"
          geometry={nodes.Object_14.geometry}
          material={materials.wire_000000013}
          skeleton={nodes.Object_14.skeleton}
          scale={15.074}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/neymar.glb");
