/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [4.86KB] > /Users/mv/Downloads/soccer_ball/scene-transformed.glb [41.17KB] (-747%)
Author: EA Sports (https://sketchfab.com/jhsgkdfhk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/soccer-ball-1122127afbf14972bbf1aaff59f353d1
Title: Soccer Ball
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function EAModel(props) {
  const { nodes, materials } = useGLTF("models/ea.glb");
  return (
    <group {...props} dispose={null} scale={[50,50,50]}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials["Material.001"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.25}
      />
      <mesh
        geometry={nodes.Object_3.geometry}
        material={materials["Material.002"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.25}
      />
    </group>
  );
}

useGLTF.preload("models/ea.glb");
