/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [97.62KB] > /Users/mv/Downloads/trebble_-_ratchet_and_clank_npc/scene-transformed.glb [1.03MB] (-952%)
Author: Mohsen Saeedi (https://sketchfab.com/etude)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/trebble-ratchet-and-clank-npc-c2c3d4b7417e44b69a4654a34bfc08cb
Title: TREBBLE - Ratchet and Clank NPC
*/

import React,{useEffect} from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function RNCModel(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("models/rnc.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    // console.log(actions)
    //idle
    const animation = actions["Take 001"];
    animation.setEffectiveWeight(100);
    animation.setLoop(true);
    animation.play();
  }, []);
  return (
    <group ref={group} {...props} dispose={null} scale={[23,23,23]} position={[0,-20,0]}>
      <group name="Sketchfab_Scene">
        <group name="Object_4" scale={0.019}>
          <group
            name="Sphere001"
            position={[0.094, 344.173, -12.075]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_40" position={[31.387, -9.355, -3.559]}>
              <mesh
                name="Sphere001_Material_#51_0"
                geometry={nodes["Sphere001_Material_#51_0"].geometry}
                material={materials.Material_51}
              />
            </group>
          </group>
          <group
            name="Sphere002"
            position={[17.156, 36.358, -12.075]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_43" position={[31.387, -9.355, -3.559]}>
              <mesh
                name="Sphere002_Material_#51_0"
                geometry={nodes["Sphere002_Material_#51_0"].geometry}
                material={materials.Material_51}
              />
            </group>
          </group>
        </group>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh
          name="Object_7"
          geometry={nodes.Object_7.geometry}
          material={materials.Material_54}
          skeleton={nodes.Object_7.skeleton}
          scale={0.019}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/rnc.glb");
