/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [575.8KB] > /Users/mv/Downloads/spider_man_playstation_rigged/scene-transformed.glb [1.42MB] (-147%)
Author: As7 3d models (https://sketchfab.com/As7312008)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spider-man-playstation-rigged-e132c0ec7eee4d1e8c8e3916bcad8085
Title: Spider man playstation (Rigged)
*/

import React,{useEffect} from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function SpidyModel(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("models/scene-transformed-spidy.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    // console.log(actions)
    //crawl, jump, swing to land
    const animation = actions["Swing to land"];
    animation.timeScale = 0.75
    animation.setEffectiveWeight(100);
    animation.setLoop(true);
    animation.play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null} scale={[13,13,13]} position={[-2, -10, 0]}>
      <group name="Sketchfab_Scene" >
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh
          name="Object_7"
          geometry={nodes.Object_7.geometry}
          material={materials["22_body_0.2_20_20"]}
          skeleton={nodes.Object_7.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_9"
          geometry={nodes.Object_9.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_9.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_11"
          geometry={nodes.Object_11.geometry}
          material={materials["22_gloves_0.2_20_20"]}
          skeleton={nodes.Object_11.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_13"
          geometry={nodes.Object_13.geometry}
          material={materials["22_head_0.2_20_20"]}
          skeleton={nodes.Object_13.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_15"
          geometry={nodes.Object_15.geometry}
          material={materials["22_legs_0.2_20_20"]}
          skeleton={nodes.Object_15.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_17"
          geometry={nodes.Object_17.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_17.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_19"
          geometry={nodes.Object_19.geometry}
          material={materials["22_shoes_0.2_20_20"]}
          skeleton={nodes.Object_19.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_21"
          geometry={nodes.Object_21.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_21.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_23"
          geometry={nodes.Object_23.geometry}
          material={materials["22_spider_0.3_20_20"]}
          skeleton={nodes.Object_23.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_25"
          geometry={nodes.Object_25.geometry}
          material={materials.PaletteMaterial002}
          skeleton={nodes.Object_25.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_27"
          geometry={nodes.Object_27.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_27.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_29"
          geometry={nodes.Object_29.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_29.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_31"
          geometry={nodes.Object_31.geometry}
          material={materials["24_webshooter_0.3_0_0"]}
          skeleton={nodes.Object_31.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_33"
          geometry={nodes.Object_33.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_33.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_35"
          geometry={nodes.Object_35.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_35.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_37"
          geometry={nodes.Object_37.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_37.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_39"
          geometry={nodes.Object_39.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_39.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_41"
          geometry={nodes.Object_41.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_41.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_43"
          geometry={nodes.Object_43.geometry}
          material={materials["27_webshooterenvred_1_0_0"]}
          skeleton={nodes.Object_43.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_45"
          geometry={nodes.Object_45.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_45.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/scene-transformed-spidy.glb");
